name: Python Package using Conda
on: [push]

jobs:
  test:
    name: Test python ${{ matrix.python-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Add conda to system path
        shell: bash
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        shell: bash
        run: |
          conda env update --file CNN.yml --name CNN
      - name: Install test packages
        shell: bash
        run: |
          pip install pytest nbconvert nbformat
      - name: which python
        shell: bash
        run: |
          which python
      - name: git info
        run: |
          git log --name-only -1 | cat -
      - name: Test with pytest
        shell: bash
        run: |
          pytest .github/workflows/test_CNN_notebooks.py
