name: Python Package using Conda
on: [push]

jobs:
  test:
    name: Test python ${{ matrix.python-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.7.10]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: CNN
          environment-file: CNN.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - shell: bash
        run: |
          conda info
          conda list
      - name: Install test packages
        shell: bash
        run: |
          pip install pytest nbconvert nbformat
      - name: which python
        shell: bash
        run: |
          which python
      - name: git info
        run: |
          git log --name-only -1 | cat -
      - name: Test with pytest
        shell: bash
        run: |
          pytest .github/workflows/test_CNN_notebooks.py
